<a href="https://colab.research.google.com/github/4522Devp/Machine_leanring_fundamentals/blob/main/Complete_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical Python = NumPy

Advantages of numPy Arrays:

1. Allows several mathematical Operations
2. faster Operations


In [ ]:
import numpy as np

List vs NumPy - TimeTaken

In [ ]:
from time import process_time

# Time taken by a List

list1 = [i for i in range(10000)]

start_time = process_time()

list1 = [i+5 for i in list1]

end_time = process_time()

print(end_time - start_time)

0.0015837489999999121


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0011834290000010128


#NumPy arrays

In [ ]:
list1 = [ 1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# creating a one dimensional array

a = np.array([1,2,3,4])
print(a)

a.shape

[1 2 3 4]


(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(type(b))
b.shape         #(row,coloumn)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


(2, 4)

In [ ]:
c =np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeHolders in numpy arrays

In [ ]:
# create a numpy array of Zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones

y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# array of a particular value

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an Identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy value with random values
b = np.random.random((3,4))
print(b)

[[0.84789772 0.82107227 0.70902264 0.98752782]
 [0.37843415 0.78072343 0.37132957 0.33985789]
 [0.43906964 0.12753575 0.82673355 0.41170252]]


In [ ]:
# random integer values array within  a specific range

c = np.random.randint(10,100,(3,4))
print(c)

[[48 64 33 47]
 [45 32 60 68]
 [48 92 34 79]]


In [ ]:
# create an array of evenly spaced values --> specifying the number of values required

d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying steps      diffrent between values

e = np.arange(10,30,6)
print(e)

[10 16 22 28]


In [ ]:
# convert a list to a numpy array

list2 = [10,20,30,40,50]

np_array = np.asarray(list2)

print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


**Analysing a Numpy Array**

In [ ]:
c = np.random.randint(10,90,(3,5))
print(c)

[[82 59 78 36 37]
 [41 32 73 46 32]
 [77 25 89 53 67]]


In [ ]:
# array dimensions
print(c.shape)

(3, 5)


In [ ]:
# no of dimension

print(c.ndim)

2


In [ ]:
# number of element in array

print(c.size)

15


In [ ]:
#checking the data typee of numpy array
print(c.dtype)

int64


**Mathematical operations on a NP array**

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # not add only join the list

In [ ]:

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[4 4 2]
 [0 8 7]
 [5 6 0]]
[[14 14 13]
 [10 11 10]
 [12 11 11]]


In [ ]:
print(a+b)  # it adds two Np array , not concadinate or join

[[18 18 15]
 [10 19 17]
 [17 17 11]]


In [ ]:

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

print(np.add(a,b))
print(np.subtract(a,b))    #it also do the same task


[[5 3 0]
 [3 0 1]
 [6 0 6]]
[[12 11 19]
 [16 16 18]
 [14 13 12]]
[[17 14 19]
 [19 16 19]
 [20 13 18]]
[[ -7  -8 -19]
 [-13 -16 -17]
 [ -8 -13  -6]]


Array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)

print(array.shape)

[[6 5 2]
 [3 3 2]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)

print(trans.shape)           # it converts row into column and column into row

[[6 3]
 [5 3]
 [2 2]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)

print(array.shape)

trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 9 3]
 [9 5 1]]
(2, 3)
[[5 9]
 [9 5]
 [3 1]]
(3, 2)


In [ ]:
#reshaping array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

print("\n")

b = a.reshape(3,2)
print(b)

[[6 7 2]
 [8 1 9]]
(2, 3)


[[6 7]
 [2 8]
 [1 9]]
